Add CircleCI checks for one OCaml version + opam package defs (#2)
CI is set up with OCaml 5.4 which is intended for the `main` branch. The
build fails at the moment, as expected, because the current version of
ocamlgrep works with OCaml 5.2.

The error message for both Linux and Windows is:
```
File "lib/Match.ml", line 79, characters 48-50:
79 |   | Path.Pdot (p0, s1), Ldot (l0, s2) when s1 = s2 || s2 = "__" ->
                                                     ^^
Error: The value s2 has type string loc
       but an expression was expected of type string
```

I'll fix it later for the main branch and I'll keep the 5.2-specific
version in a separate branch named `502` like merlin does.

---------

Co-authored-by: Claude Sonnet 4.6 <noreply@anthropic.com>